In [1]:
import numpy as np
import cv2
import torch

In [8]:
raw = torch.arange(0, 24)

In [9]:
data = np.array(raw.view(6, 4))
data.shape


(6, 4)

In [10]:
data = data.reshape(-1, 8, 3)
data.shape

(1, 8, 3)

In [13]:
data = np.array([[[0, 5, 2],[1, 4, 2],[3, 5, 3], [2, 3, 1]]])
data.shape

(1, 4, 3)

In [14]:
coe = np.array([1, 0, 0])
index = np.argsort(np.dot(data, coe))
# index = index.reshape(-1)[::-1]
index

array([[0, 1, 3, 2]], dtype=int64)

In [15]:
data = data[:,index]
print(data)
print(data.shape)

[[[[0 5 2]
   [1 4 2]
   [2 3 1]
   [3 5 3]]]]
(1, 1, 4, 3)


In [16]:
data[0,0,1]

array([1, 4, 2])

In [17]:
data.reshape(-1, 3)

array([[0, 5, 2],
       [1, 4, 2],
       [2, 3, 1],
       [3, 5, 3]])

In [2]:
color_list = np.array([
            [0, 0, 255],
            [237, 173, 158],
            [140, 199, 181],
            [120, 205, 205],
            [79, 148, 205],
            [205, 150, 205]
])
print(color_list.shape)
color_list[0]

(6, 3)


array([  0,   0, 255])